spring.application.name=controlevestuario
spring.jpa.open-in-view=true

# Configurações do banco de dados SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ControleVestuario;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=aluno
spring.datasource.password=dba
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Mude para update para ele manter e estruturar suas tabelas sem apagar o banco toda hora
spring.jpa.hibernate.ddl-auto=create-drop

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true