spring.application.name=controlevestuario
spring.jpa.open-in-view=true

# Configurações do banco de dados SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ControleVestuario;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=aluno
spring.datasource.password=dba
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Banco gerenciado pelo script SQL. Não usar create-drop para não apagar views, triggers e procedures.
spring.jpa.hibernate.ddl-auto=none

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true